default:
  url: "http://weaviate:8080"
  vector_index_config:
    distance: "cosine"
    efConstruction: 128
    maxConnections: 64
  batch_size: 100
  retry_attempts: 3
  retry_delay: 5
  esco:
    data_dir: "data/esco"
    batch_size: 100

aura:
  url: "http://weaviate:8080"
  vector_index_config:
    distance: "cosine"
    efConstruction: 128
    maxConnections: 64
  batch_size: 100
  retry_attempts: 5
  retry_delay: 10
  esco:
    data_dir: "data/esco"
    batch_size: 100 